// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSession() {
  return window['go']['main']['App']['CheckSession']();
}

export function CreateCategoryClient(arg1) {
  return window['go']['main']['App']['CreateCategoryClient'](arg1);
}

export function CreateItemClient(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateItemClient'](arg1, arg2, arg3);
}

export function DecryptAES256GCM(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptAES256GCM'](arg1, arg2, arg3);
}

export function DeleteCategoryClient(arg1) {
  return window['go']['main']['App']['DeleteCategoryClient'](arg1);
}

export function EmailToSHA256(arg1) {
  return window['go']['main']['App']['EmailToSHA256'](arg1);
}

export function EncryptAES256GCM(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptAES256GCM'](arg1, arg2, arg3);
}

export function GenerateIV() {
  return window['go']['main']['App']['GenerateIV']();
}

export function GenerateSessionKey() {
  return window['go']['main']['App']['GenerateSessionKey']();
}

export function GetCategoryList() {
  return window['go']['main']['App']['GetCategoryList']();
}

export function GetPasswordList() {
  return window['go']['main']['App']['GetPasswordList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoginUser(arg1, arg2) {
  return window['go']['main']['App']['LoginUser'](arg1, arg2);
}

export function LogoutUser() {
  return window['go']['main']['App']['LogoutUser']();
}

export function PBKDF2Function(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PBKDF2Function'](arg1, arg2, arg3, arg4);
}

export function RecoveryProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecoveryProcess'](arg1, arg2, arg3);
}

export function RecoverySetup(arg1) {
  return window['go']['main']['App']['RecoverySetup'](arg1);
}

export function RegisterUser(arg1, arg2) {
  return window['go']['main']['App']['RegisterUser'](arg1, arg2);
}

export function SimplePOC(arg1) {
  return window['go']['main']['App']['SimplePOC'](arg1);
}

export function ToggleBookmark(arg1, arg2) {
  return window['go']['main']['App']['ToggleBookmark'](arg1, arg2);
}

export function UpdateItemClient(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateItemClient'](arg1, arg2, arg3, arg4);
}
