// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAES256GCM(arg1:Array<number>,arg2:Array<number>,arg3:Array<number>):Promise<Array<number>>;

export function EmailToSHA256(arg1:string):Promise<string>;

export function EncryptAES256GCM(arg1:Array<number>,arg2:Array<number>,arg3:Array<number>):Promise<Array<number>>;

export function GenerateIV():Promise<Array<number>>;

export function GenerateSessionKey():Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;

export function LoginUser(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function PBKDF2Function(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function RegisterUser(arg1:string,arg2:string):Promise<string>;

export function SimplePOC(arg1:string):Promise<void>;
