// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAES256GCM(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptAES256GCM'](arg1, arg2, arg3);
}

export function EmailToSHA256(arg1) {
  return window['go']['main']['App']['EmailToSHA256'](arg1);
}

export function EncryptAES256GCM(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptAES256GCM'](arg1, arg2, arg3);
}

export function GenerateIV() {
  return window['go']['main']['App']['GenerateIV']();
}

export function GenerateSessionKey() {
  return window['go']['main']['App']['GenerateSessionKey']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PBKDF2Function(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PBKDF2Function'](arg1, arg2, arg3, arg4);
}

export function SimplePOC(arg1) {
  return window['go']['main']['App']['SimplePOC'](arg1);
}
