// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function PBKDF2Function(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function SimplePOC(arg1:string):Promise<void>;
